apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: haproxy
  namespace: networking
spec:
  interval: 24h
  url: https://haproxytech.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy-kubernetes-ingress
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: kubernetes-ingress
      version: 1.40.0
      sourceRef:
        kind: HelmRepository
        name: haproxy
        namespace: networking
      interval: 12h
  values:
    controller:
      service:
        type: "LoadBalancer"
      replicaCount: 1
      logging:
        level: "trace"