---
version: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  path: ../../base/cert-manager/app
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    - patch: |
        - op: add
          path: /metadata/namespace
          value: cert-manager
      target: 
        kind: HelmRepository
        name: cert-manager
    - patch: |
        - op: add
          path: /metadata/namespace
          value: cert-manager
        - op: add
          path: /spec/chart/spec/sourceRef/namespace
          value: cert-manager
      target:
        kind: HelmRelease
        name: cert-manager
      