---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  path: controllers/base/cert-manager/app
  prune: true
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    - target:
        kind: HelmRepository
        name: cert-manager
      patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1beta1
        kind: HelmRepository
        metadata:
          namespace: cert-manager
    - target:
        kind: HelmRelease
        name: cert-manager
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          namespace: cert-manager
        spec:
          chart:
            spec:
              sourceRef:
                namespace: cert-manager