---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-certs
  namespace: flux-system
spec:
  prune: true
  path: controllers/base/cert-manager/certs
  dependsOn:
    - name: cert-manager
      namespace: flux-system
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    - target:
        kind: Certificate
        name: certificate-tls
      patch: |-
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          namespace: cert-manager
        spec:
          dnsNames:
            - "shoplist.staging.lazebny.io"
            - "*.shoplist.staging.lazebny.io"
    - target:
        kind: ClusterIssuer
        name: tls-issuer
      patch: |-
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          namespace: cert-manager
        spec:
          acme:
            email: miskadl09@gmail.com
            server: https://acme-v02.api.letsencrypt.org/directory
            privateKeySecretRef:
              name: tls-issuer-account-key
            solvers:
              - dns01:
                  cloudflare:
                    email: miskadl09@gmail.com
                    apiTokenSecretRef:
                      name: cloudflare-api-token
                      key: api-token