---
version: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-certs
  namespace: flux-system
spec:
  path: ../../base/cert-manager/certs
  dependsOn:
    - name: cert-manager
      namespace: flux-system
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    - patch: |
        - op: replace
          path: /metadata/namespace
          value: cert-manager
        - op: replace
          path: /spec/dnsNames
          value:
            - "shoplist.staging.lazebny.io"
            - "*.shoplist.staging.lazebny.io"
      target:
        kind: Certificate
        name: certificate-tls
    - patch: |
        - op: replace
          path: /metadata/namespace
          value: cert-manager
        - op: replace
          path: /spec/acme
          value:
            # Replace the email address with your own contact email
            email: miskadl09@gmail.com
            server: https://acme-v02.api.letsencrypt.org/directory
            privateKeySecretRef:
              name: tls-issuer-account-key
            solvers:
              - dns01:
                  cloudflare:
                    email: miskadl09@gmail.com
                    apiTokenSecretRef:
                      name: cloudflare-api-token
                      key: api-token
      target:
        kind: ClusterIssuer
        name: tls-issuer
