apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-certs
  namespace: flux-system
spec:
  prune: true
  path: controllers/base/cert-manager/certs
  dependsOn:
    - name: cert-manager
      namespace: flux-system
  interval: 5m0s
  timeout: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    - target:
        kind: Certificate
        name: certificate-tls
      patch: |
        - op: add
          path: /metadata/namespace
          value: cert-manager
        - op: add
          path: /spec/dnsNames
          value:
            - "shoplist.staging.lazebny.io"
            - "*.shoplist.staging.lazebny.io"
    - target:
        kind: ClusterIssuer
        name: tls-issuer
      patch: |
        - op: add
          path: /metadata/namespace
          value: cert-manager
        - op: add
          path: /spec/acme/email
          value: miskadl09@gmail.com
        - op: add
          path: /spec/acme/server
          value: https://acme-v02.api.letsencrypt.org/directory
        - op: add
          path: /spec/acme/privateKeySecretRef/name
          value: tls-issuer-account-key
        - op: add
          path: /spec/acme/solvers
          value:
            - dns01:
                cloudflare:
                  email: miskadl09@gmail.com
                  apiTokenSecretRef:
                    name: cloudflare-api-token
                    key: api-token