apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager
  - cloudflare-api-token.sops.yaml
patches:
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
    path: certs-patch.yaml
