apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-api-token.sops.yaml
  - ../../base/cert-manager
patches:
  - target:
      name: certs
      kind: Kustomization
    path: certs-patch.yaml
