apiVersion: v1
data:
    access-key-id: ENC[AES256_GCM,data:73W0Gg1i91R1gxILDrvmKNEzKZajXnS4Al4hA53GUYxLy4RTeF+NKqVWYwc=,iv:Uom3VoaC1HeEOHJ1wcgzR/+GmiR2HENY33zehHho37k=,tag:DyMFDl4RjhcCh/9DxkcU4Q==,type:str]
    secret-access-key: ENC[AES256_GCM,data:PMdHPiGGUQrsh1P4h36okK9ZRkVSmB+o47czHhe9vsgRXSbwl3HmH8lyNFGa/BdfgOJFKK4q/QdAI9JWO/kMAv7Upga5iKdIfDLkUdkeCOwO0o0mKhgoyg==,iv:Mky/aDcUGTi6V3k5/AD5E7p8cAjMKPlQaG/7aA5pOqI=,tag:VhICvIdHpmWdXrAbtLkinQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: s3-credentials
    namespace: keycloak
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age138n2u0dgdzqplz32uthrwf0dhr3k7ugzu3slluw9jtuzdkvrzstsj0hx4v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd2Q4bGZFVmZxbFlHMXZF
            TDkrQ1diWXpUb1BGUUlYeXR4N2FzZTQ3WkNRCnlURjgzQ0d4a3h4T0kwaFd1Ky9H
            emZIN093cWMzUDRKV283QkpYRjd0SGsKLS0tIExPdDVDenVMM0I0bWRXbjNjUVNN
            Z0doaWFlZ29CYlZrTlJCbGZxVXY3QXMKObuBnzJGATEfBOa6zptXToCAIaDyFtAA
            ymTIHaYuy2JSpDHHVIUvkWvZkJy7GutnlUUCPffGsjIyNI8qDZnDSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T13:48:10Z"
    mac: ENC[AES256_GCM,data:820Sp91ksLiEvgB9ILAn4lJb5tNUgNRoiJ9orO56kTmN+9Hvyd4JYGuvLSTukakRKO2yuregi4106N2accXh9QCPTjPZNiSng7NFa5pXd3mdXgNnYT+67G1YiVu4e7esLBN+bEMh1E9Kh+In6Lzt0uat4wjuMhN3kV5sPUAsGEs=,iv:glV8f1tADKiAN7HaLA/BkkygYCXT3CeDZ7i7VQ5Lxj0=,tag:CtcQbjiqKi6/AsqYQNig1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
