apiVersion: v1
kind: Secret
metadata:
    name: s3-creds
    namespace: keycloak
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:LLvjcVbJ0Q5FoERiRkPFe8hRPqdxRQW1p5jWRDpcsBU=,iv:XFCelzQS0w1AX2Gv6AWPI804eB9Fz2zAIl8I63BkW2g=,tag:ALdmgei5vzcZwhJf07CTPA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:jiFBn3NG/twQTL+NZKE5zMxMQ8WKDOhnfFa2uk1CES9rfetfF+4xFyjzlAxtsRQyXdOgkR9lxaSWiCIql4x3Ag==,iv:vHgMCRfTGJLjzn6KzuumJLvXT8sHC8VNmWfgfPWj/+0=,tag:JPjvjvl7IeTJNLXkEbFDsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age138n2u0dgdzqplz32uthrwf0dhr3k7ugzu3slluw9jtuzdkvrzstsj0hx4v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU3JHanFYTVQyRmtyTzNw
            OFp5OW55V29CVmgrQnM0VHdMRlJRc3pPd1Z3Ck1tUy82eHZPMllxd05GSVFsMHdW
            WmJIUEhORHVLZ0UyMU5jUzR6Smk3R1kKLS0tIG4zNklsaWxhWi9TY2tmRExMWGVt
            aWZCZFhGT2pRZWRmRHZpb0dRUk1oeUkKafUECv71JaSzrGL5x0cvKhqa0lKAQgdy
            C2CENwkwABefqx37I25xDa1TIZKbA/ByhneNFaHE8LRr9OmQWd5EZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T19:45:06Z"
    mac: ENC[AES256_GCM,data:TDHWmJTCV+Hw1lP2KQ3Y1GZplJ6n8hTkKwZGNtxOQiK2LfTwyd63PYCD2WDSrmpw8ReYsRbLIUc3mCuFIOx1fVvaIGwrKtRCJcqJo0xfJOe4vNzFuT014ca4706J7UITcVrR4dgSZnmlfMoShrZUPlKfQS6ZbmGAOtdlahUF2nI=,iv:rZUBtW+MaaNDjK4eFqZKedjJBEc+oMSRkRq3B0cZ/v8=,tag:9AHmKa9iBFc66nBewFqgSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
