apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-tls
  namespace: networking
spec:
  secretName: certificate-tls
  commonName: "shoplist.staging.lazebny.io"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - "shoplist.staging.lazebny.io"
  - "*.shoplist.staging.lazebny.io"
