---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certs
  namespace: cert-manager
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/cert-manager/certs
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  prune: true
  wait: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |-
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: certificate-tls
          namespace: cert-manager
        spec:
          secretName: certificate-tls
          commonName: "shoplist.staging.lazebny.io"
          secretTemplate:
            annotations:
              reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
              reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          issuerRef:
            name: tls-issuer
            kind: ClusterIssuer
            group: cert-manager.io
          dnsNames:
          - "shoplist.staging.lazebny.io"
          - "*.shoplist.staging.lazebny.io"
      target:
        kind: Certificate
        name: certificate-tls
    - patch: |-
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: tls-issuer
          namespace: cert-manager
        spec:
          acme:
            # Replace the email address with your own contact email
            email: miskadl09@gmail.com
            server: https://acme-v02.api.letsencrypt.org/directory
            privateKeySecretRef:
              name: tls-issuer-account-key
            solvers:
              - dns01:
                  cloudflare:
                    email: miskadl09@gmail.com
                    apiTokenSecretRef:
                      name: cloudflare-api-token
                      key: api-token
      target:
        kind: ClusterIssuer
        name: tls-issuer
