---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tls-issuer
  namespace: cert-manager
spec:
  acme:
    # Replace the email address with your own contact email
    email: miskadl09@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tls-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: miskadl09@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token