apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ../../base/cert-manager
  - cloudflare-api-token.sops.yaml
patches:
  - path: certificate-patch.yaml
    target:
      kind: Certificate

  - path: cluster-issuer-patch.yaml
    target:
      kind: ClusterIssuer
      name: tls-issuer
