apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: certs
namespace: networking
resources:
  - cloudflare-api-token.sops.yaml
  - cluster-issuers.yaml
  - certificate.yaml