apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  # Forward HTTPS to Keycloak
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "keycloak.shoplist.staging.lazebny.io"
        - "keycloak-admin.shoplist.staging.lazebny.io"
      secretName: certificate-tls
  rules:
    - host: "keycloak.shoplist.staging.lazebny.io"
      http:
        paths:
          - backend:
              service:
                name: keycloak-service
                port:
                  number: 8443
            path: /
            pathType: Prefix
    - host: "keycloak-admin.shoplist.staging.lazebny.io"
      http:
        paths:
          - backend:
              service:
                name: keycloak-service
                port:
                  number: 9000
            path: /
            pathType: Prefix
