apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  path: apps/base/keycloak/keycloak
  dependsOn:
    - name: keycloak-operator
    - name: keycloak-postgres
  prune: true
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    - target:
        name: keycloak
        kind: Keycloak
      patch: |-
        apiVersion: k8s.keycloak.org/v2alpha1
        kind: Keycloak
        metadata:
          name: keycloak
          namespace: keycloak
        spec:
          instances: 1
          db:
            vendor: postgres
            passwordSecret:
              name: keycloak-postgres-user
              key: password
            usernameSecret:
              name: keycloak-postgres-user
              key: username
            database: app
            port: 5432
            host: keycloak-postgres-rw.keycloak.svc.cluster.local
          ingress:
            enabled: false
          http:
            tlsSecret: certificate-tls
          hostname:
            hostname: "https://keycloak.shoplist.staging.lazebny.io"
          additionalOptions:
            - name: LOG_LEVEL
              value: ALL
            - name: HEALTH_ENABLED
              value: "true"
          unsupported:
            podTemplate:
              spec:
                containers:
                  - 
                    livenessProbe:
                      httpGet:
                        path: /health/live
                        port: 9000
                        scheme: HTTP
                      initialDelaySeconds: 20
                      periodSeconds: 2
                      successThreshold: 1
                      timeoutSeconds: 1
                      failureThreshold: 150

                    readinessProbe:
                      httpGet:
                        path: /health/ready
                        port: 9000
                        scheme: HTTP
                      initialDelaySeconds: 20
                      periodSeconds: 2
                      successThreshold: 1
                      timeoutSeconds: 1
                      failureThreshold: 250

                    startupProbe:
                      httpGet:
                        path: /health/ready
                        port: 9000
                        scheme: HTTP
                      initialDelaySeconds: 60
                      periodSeconds: 2
                      successThreshold: 1
                      timeoutSeconds: 1
                      failureThreshold: 250
