apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  additionalOptions:
    - name: KC_LOG_LEVEL
      value: ALL
  hostname:
    strict: false
    strictBackchannel: false