---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  prune: true
  patches:
    - patch: |
        - op: replace
          path: /spec/acme/server
          value: https://acme-v02.api.letsencrypt.org/directory
      target:
        kind: ClusterIssuer
        name: letsencrypt-issuer
    - patch: |
        - op: replace
          path: /spec/dnsNames
          value:
            - "shoplist.staging.lazebny.io"
            - "shoplist.staging.podinfo.lazebny.io"
        - op: replace
          path: /spec/commonName
          value: "shoplist.staging.lazebny.io"
      target:
        kind: Certificate
        name: shoplist-lazebny-io-tls
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)
  decryption:
    provider: sops
    secretRef:
      name: sops-age