apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  path: apps/base/podinfo
  prune: true
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    - target:
        kind: HelmRelease
        name: podinfo
      patch: |-
        - op: replace
          path: /spec/values
          value:
            ingress:
              enabled: true
              annotations:
                nginx.ingress.kubernetes.io/auth-tls-secret: "podinfo/certificate-tls"
                nginx.ingress.kubernetes.io/rewrite-target: /$1
              hosts:
              - host: podinfo.shoplist.staging.lazebny.io
                paths:
                - path: /(.*)
                  pathType: Prefix
              tls:
              - secretName: certificate-tls
                hosts:
                - "podinfo.shoplist.staging.lazebny.io"