apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    ingress:
      className: haproxy
      hosts:
        - host: shoplist.staging.podinfo.lazebny.io
          paths:
            - path: /(.*)
              pathType: Prefix
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
      tls:
        - secretName: tls-secret
          hosts:
            - shoplist.staging.podinfo.lazebny.io
            - shoplist.staging.lazebny.io