apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    ingress:
      enabled: true
      className: haproxy
      annotations:
        haproxy.org/path-rewrite: /(.*) /$1
        cert-manager.io/cluster-issuer: letsencrypt-issuer
      hosts:
        - host: shoplist.staging.podinfo.lazebny.io
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: tls-secret
          hosts:
            - shoplist.staging.podinfo.lazebny.io
            - shoplist.staging.lazebny.io