apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: reflector
  namespace: kube-system
spec:
  interval: 15m
  url: https://emberstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: kube-system
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: kube-system
