apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
spec:
  instances: 1

  backup:
    retentionPolicy: 7d
    barmanObjectStore: &barman
      serverName: &current-cluster cluster-v3
      destinationPath: "s3://shoplist-staging-backups"
      endpointURL: "https://d2e1470eded3cd2e7a93cc3f69f34558.r2.cloudflarestorage.com"
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      s3Credentials:
        accessKeyId:
          name: &s3-secret s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: *s3-secret
          key: ACCESS_SECRET_KEY

  # if it is needed to recover from a backup, uncomment the following lines
  # bootstrap:
  #   recovery:
  #     database: app
  #     owner: app
  #     source: &prev-cluster cluster-v2
  # externalClusters:
  #   - name: *prev-cluster
  #     barmanObjectStore:
  #       <<: *barman
  #       serverName: *prev-cluster
