apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-cluster
spec:
  instances: 2
  bootstrap:
    recovery:
      database: app
      owner: app
      source: &prev-cluster test-cluster-recover

  backup:
    retentionPolicy: 7d
    barmanObjectStore:
      destinationPath: &s3-bucket "s3://shoplist-staging-backups"
      endpointURL: &s3-host "https://d2e1470eded3cd2e7a93cc3f69f34558.r2.cloudflarestorage.com"
      wal:
        compression: &compression bzip2
        maxParallel: &parallel 8
      s3Credentials:
        accessKeyId:
          name: &s3-secret s3-creds
          key: &access-key ACCESS_KEY_ID
        secretAccessKey:
          name: *s3-secret
          key: &secret-key ACCESS_SECRET_KEY

  externalClusters:
    - name: *prev-cluster
      barmanObjectStore:
        destinationPath: *s3-bucket
        endpointURL: *s3-host
        wal:
          compression: *compression
          maxParallel: *parallel
        s3Credentials:
          accessKeyId:
            name: *s3-secret
            key: *access-key
          secretAccessKey:
            name: *s3-secret
            key: *secret-key
