apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster
resources:
- app-secret.yaml
- superuser-secret.yaml
- ../../base/cluster
patches:
- path: cluster-patch.yaml
  target:
    kind: Cluster
    name: cluster
