---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # Replace the email address with your own contact email
    email: miskadl09@gmail.com
    # The server is replaced in /clusters/staging/infrastructure.yaml
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx
    solvers:
      - dns01:
          cloudflare:
            email: miskadl09@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token