apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 30m
  dependsOn:
    - name: infra
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: networking
      interval: 12h
  values:
    controller:
      service:
        type: "LoadBalancer"
    admissionWebhooks:
      enabled: false
    default-ssl-certificate:
      secretName: shoplist-lazebny-io-tls